version: '3'
services:

  app:
    build: .
    container_name: app
    image: app
    # environment:
      # DISABLE_SWAGGER_HTTP_HANDLER: 'false'
    ports:
      - 8000:8080
    networks:
      - database

  # integration:
  #   build:
  #     context: .
  #     dockerfile: integration-test/Dockerfile
  #   container_name: integration
  #   image: integration
  #   depends_on:
  #     - app

networks:
  database:
    external: true
    name: database